export type MenuItem = {
    name: string;
    price: string;
    description?: string;
    isVeg?: boolean;
};

export type MenuCategory = {
    title: string;
    items: MenuItem[];
};

export const MENU_DATA: MenuCategory[] = [
    {
        title: "South Indian Breakfast",
        items: [
            { name: "Idly (2)", price: "0.500", isVeg: true },
            { name: "Idly (2) Sambar Dip", price: "0.600", isVeg: true },
            { name: "Vada (1)", price: "0.300", isVeg: true },
            { name: "Vada (1) Sambar Dip", price: "0.400", isVeg: true },
            { name: "Idly (1) & Vada (1)", price: "0.550", isVeg: true },
            { name: "Idly (1) & Vada (1) Sambar Dip", price: "0.700", isVeg: true },
            { name: "Idly (2) & Vada (1)", price: "0.800", isVeg: true },
            { name: "Idly (2) & Vada (1) Sambar Dip", price: "1.000", isVeg: true },
            { name: "Rava Idly (1)", price: "0.650", isVeg: true },
            { name: "Khara Bath", price: "0.800", isVeg: true },
            { name: "Kesari Bath", price: "0.700", isVeg: true },
            { name: "Curd Vada", price: "0.550", isVeg: true },
            { name: "Chow Chow Bath", price: "1.400", isVeg: true },
            { name: "Poori Saagu (3)", price: "0.850", isVeg: true },
            { name: "Mangalore Buns (1)", price: "0.400", isVeg: true },
            { name: "Ghee Rice (Monday)", price: "0.750", isVeg: true },
            { name: "Lemon Rice (Tuesday)", price: "0.750", isVeg: true },
            { name: "Bisibelebath (Wed & Fri)", price: "0.850", isVeg: true },
            { name: "Veg Pulav (Thursday)", price: "0.750", isVeg: true },
            { name: "Pongal (Saturday)", price: "0.850", isVeg: true },
            { name: "Tomato Rice (Sunday)", price: "0.750", isVeg: true },
        ],
    },
    {
        title: "World of Dosas",
        items: [
            { name: "Khali Dosa (2)", price: "0.900", isVeg: true },
            { name: "Set Dosa (2)", price: "1.000", isVeg: true },
            { name: "Plain Dosa", price: "0.800", isVeg: true },
            { name: "Butter Plain Dosa", price: "1.000", isVeg: true },
            { name: "Ghee Roast", price: "1.000", isVeg: true },
            { name: "Pudi Plain", price: "0.900", isVeg: true },
            { name: "Ghee Pudi Plain", price: "1.100", isVeg: true },
            { name: "Masala Dosa", price: "1.000", isVeg: true },
            { name: "Butter Masala Dosa", price: "1.200", isVeg: true },
            { name: "Ghee Masala Dosa", price: "1.200", isVeg: true },
            { name: "Mysore Masala Dosa", price: "1.200", isVeg: true },
            { name: "Ghee Mysore Masala Dosa", price: "1.350", isVeg: true },
            { name: "Davangere Benne Dosa", price: "1.450", isVeg: true },
            { name: "Onion Dosa", price: "1.100", isVeg: true },
            { name: "Open Butter Masala", price: "1.300", isVeg: true },
            { name: "Paper Plain Dosa", price: "1.600", isVeg: true },
            { name: "Paper Masala Dosa", price: "1.800", isVeg: true },
            { name: "Rava Dosa", price: "0.900", isVeg: true },
            { name: "Rava Masala Dosa", price: "1.000", isVeg: true },
            { name: "Rava Onion Dosa", price: "1.000", isVeg: true },
            { name: "Rava Onion Masala Dosa", price: "1.100", isVeg: true },
            { name: "Paneer Masala Dosa (Evening)", price: "1.300", isVeg: true },
            { name: "Pesarattu (Monday)", price: "1.100", isVeg: true },
            { name: "Neer Dosa (Tue & Sat)", price: "1.000", isVeg: true },
            { name: "Sagu Masala Dosa (Wed)", price: "1.000", isVeg: true },
            { name: "Ragi Dosa (Thursday)", price: "0.900", isVeg: true },
            { name: "Pineapple Dosa (Friday)", price: "1.000", isVeg: true },
            { name: "Cucumber Dosa (Sunday)", price: "0.900", isVeg: true },
        ],
    },
    {
        title: "Combos & Meals",
        items: [
            {
                name: "Combo Breakfast",
                price: "1.500",
                description: "Idly - 1 pcs, Mini Vada - 1 pcs, Mini Masala Dosa, Khara Bath, Kesari Bath, Rice Bath of the Day & Mini Coffee (7 AM to 12 Noon)",
                isVeg: true
            },
            {
                name: "Mini Combo Breakfast",
                price: "1.000",
                description: "Idly - 1 pcs, Mini Vada - 1 pcs, Mini Masala Dosa, Khara Bath or Rice Bath of the Day & Mini Coffee (7 AM to 12 Noon)",
                isVeg: true
            },
            {
                name: "Quick Lunch (Limited)",
                price: "1.000",
                description: "Rice, Sambaar, Rasam, Daal, Palya, Curd, Papad, Pickle (12 PM to 3 PM)",
                isVeg: true
            },
            {
                name: "South Indian Executive Meals",
                price: "1.400",
                description: "Chapathi - 2 pcs or Mini Poori - 3 pcs, Sagu, Rice, Sambar, Rasam, Daal, Palya, Bajji, Sweet, Curd, Chutney, Papad, Pickle (12 PM to 3 PM)",
                isVeg: true
            },
            {
                name: "Ragi Mudde Oota (Thursdays)",
                price: "1.200",
                description: "Ragi Mudde - 2 pcs, Sambaar, Rasam, Palya, Salad",
                isVeg: true
            },
            { name: "Curd Rice", price: "0.750", isVeg: true },
            { name: "Chapathi - 3 Pcs with Sagu", price: "0.850", isVeg: true },
            {
                name: "North Indian Meals",
                price: "1.800",
                description: "Soup, Tandoori Roti - 2 pcs, Paneer Curry, Daal, Dry Sabzi, Biriyani, Sweet, Raita, Roasted Papad, Salad (12 PM to 3 PM)",
                isVeg: true
            },
        ],
    },
    {
        title: "Chaats & Snacks",
        items: [
            { name: "Masala Puri", price: "0.900", isVeg: true },
            { name: "Bhel Puri", price: "0.900", isVeg: true },
            { name: "Pakodi Bhel", price: "1.000", isVeg: true },
            { name: "Pani Puri", price: "0.800", isVeg: true },
            { name: "Dahi Puri", price: "0.900", isVeg: true },
            { name: "Sev Puri", price: "0.900", isVeg: true },
            { name: "Aloo Puri", price: "0.900", isVeg: true },
            { name: "Dahi Papdi Chat", price: "0.900", isVeg: true },
            { name: "Pineapple Chat", price: "1.000", isVeg: true },
            { name: "Vada Pav", price: "0.650", isVeg: true },
            { name: "Butter Vada Pav", price: "0.750", isVeg: true },
            { name: "Pav Bhaji", price: "0.900", isVeg: true },
            { name: "Cheese Pav Bhaji", price: "1.100", isVeg: true },
            { name: "Paneer Pav Bhaji", price: "1.200", isVeg: true },
            { name: "Bonda Soup (2)", price: "0.700", isVeg: true },
            { name: "Goli Bajji (4)", price: "0.500", isVeg: true },
            { name: "Bonda (2)", price: "0.500", isVeg: true },
            { name: "Bajji (4)", price: "0.700", isVeg: true },
            { name: "Akki Rotti (2)", price: "1.000", isVeg: true },
            { name: "Ragi Rotti (2)", price: "1.000", isVeg: true },
            { name: "Shavige Bath (Weekends)", price: "0.900", isVeg: true },
        ],
    },
    {
        title: "Chinese Starters",
        items: [
            { name: "Crispy Corn Chilli", price: "1.800", isVeg: true },
            { name: "Honey Chilli Potato", price: "1.700", isVeg: true },
            { name: "Veg Ball Manchurian", price: "1.800", isVeg: true },
            { name: "Gobi Manchurian/Chilli/Pepper Dry/65", price: "1.800", isVeg: true },
            { name: "Babycorn Manchurian/Chilli/Pepper Dry/65", price: "1.900", isVeg: true },
            { name: "Mushroom Manchurian/Chilli/Pepper Dry/65", price: "1.900", isVeg: true },
            { name: "Paneer Manchurian/Chilli/Pepper Dry/65", price: "2.000", isVeg: true },
            { name: "Spring Rolls", price: "1.300", isVeg: true },
            { name: "Corn 'n' Cheese Spring Rolls", price: "1.600", isVeg: true },
            { name: "Fries", price: "0.750", isVeg: true },
            { name: "Cream of Tomato Soup", price: "1.000", isVeg: true },
            { name: "Sweet Corn Soup", price: "1.000", isVeg: true },
            { name: "Lemon Coriander Soup", price: "1.000", isVeg: true },
            { name: "Hot 'n' Sour Soup", price: "1.000", isVeg: true },
            { name: "Veg Manchow Soup", price: "1.000", isVeg: true },
            { name: "Veg Noodles Soup", price: "1.000", isVeg: true },
            { name: "Mushroom Soup", price: "1.100", isVeg: true },
        ],
    },
    {
        title: "Rice & Noodles",
        items: [
            { name: "Veg Fried Rice", price: "1.500", isVeg: true },
            { name: "Paneer Fried Rice", price: "1.800", isVeg: true },
            { name: "Mushroom Fried Rice", price: "1.800", isVeg: true },
            { name: "Schezwan Fried Rice", price: "1.600", isVeg: true },
            { name: "Triple Fried Rice", price: "2.300", isVeg: true },
            { name: "Chilli Garlic Fried Rice", price: "1.650", isVeg: true },
            { name: "Veg Hakka Noodles", price: "1.500", isVeg: true },
            { name: "Schezwan Noodles", price: "1.650", isVeg: true },
            { name: "Mushroom Noodles", price: "1.800", isVeg: true },
            { name: "Chilli Garlic Noodles", price: "1.650", isVeg: true },
            { name: "Ginger Garlic Noodles", price: "1.650", isVeg: true },
        ],
    },
    {
        title: "Tandoori Starters",
        items: [
            { name: "Fried/Roasted Papad", price: "0.200", isVeg: true },
            { name: "Masala Papad", price: "0.400", isVeg: true },
            { name: "Tandoori Babycorn", price: "1.800", isVeg: true },
            { name: "Hara Bhara Kabab", price: "1.900", isVeg: true },
            { name: "Makai Tikka", price: "1.900", isVeg: true },
            { name: "Tandoori Aloo Tikka", price: "1.600", isVeg: true },
            { name: "Mushroom Tikka", price: "2.000", isVeg: true },
            { name: "Tandoori Platter", price: "3.800", isVeg: true },
            { name: "Paneer Tikka", price: "2.100", isVeg: true },
            { name: "Pahadi Paneer Tikka", price: "2.100", isVeg: true },
            { name: "Paneer Malai Tikka", price: "2.200", isVeg: true },
        ],
    },
    {
        title: "North Indian Curries",
        items: [
            { name: "Paneer Butter Masala", price: "1.900", isVeg: true },
            { name: "Paneer Tikka Masala", price: "2.200", isVeg: true },
            { name: "Paneer Pudina Masala", price: "1.900", isVeg: true },
            { name: "Paneer Burji", price: "2.200", isVeg: true },
            { name: "Shahi Paneer", price: "2.000", isVeg: true },
            { name: "Paneer Pasanda", price: "2.200", isVeg: true },
            { name: "Mutter Paneer", price: "1.800", isVeg: true },
            { name: "Kadai Paneer", price: "1.900", isVeg: true },
            { name: "Paneer Kolhapuri", price: "2.000", isVeg: true },
            { name: "Paneer Lazeez", price: "2.000", isVeg: true },
            { name: "Paneer Lababdar", price: "1.800", isVeg: true },
            { name: "Palak Paneer", price: "1.800", isVeg: true },
            { name: "Plain Palak", price: "1.400", isVeg: true },
            { name: "Aloo Palak", price: "1.600", isVeg: true },
            { name: "Veg Hyderabadi", price: "1.600", isVeg: true },
            { name: "Aloo Methi", price: "1.300", isVeg: true },
            { name: "Aloo Gobi", price: "1.500", isVeg: true },
            { name: "Aloo Mutter", price: "1.450", isVeg: true },
            { name: "Aloo Jeera Dry", price: "1.300", isVeg: true },
            { name: "Dum Aloo Punjabi", price: "1.600", isVeg: true },
            { name: "Daal Fry", price: "1.400", isVeg: true },
            { name: "Daal Tadka", price: "1.500", isVeg: true },
            { name: "Daal Makhani", price: "1.600", isVeg: true },
            { name: "Daal Palak", price: "1.600", isVeg: true },
            { name: "Mix Veg Curry", price: "1.400", isVeg: true },
            { name: "Veg Kadai", price: "1.750", isVeg: true },
            { name: "Veg Kurma", price: "1.550", isVeg: true },
            { name: "Veg Kolhapuri", price: "1.700", isVeg: true },
            { name: "Veg Do-Pyaza", price: "1.600", isVeg: true },
            { name: "Veg Patiyala", price: "1.800", isVeg: true },
            { name: "Veg Jaipuri", price: "1.700", isVeg: true },
            { name: "Veg Kofta", price: "1.550", isVeg: true },
            { name: "Malai Kofta", price: "1.800", isVeg: true },
            { name: "Malai Methi Mutter", price: "1.700", isVeg: true },
            { name: "Ashoka Grand Spl Curry", price: "1.900", isVeg: true },
            { name: "Kaju Masala", price: "2.000", isVeg: true },
            { name: "Kaju Mushroom", price: "2.300", isVeg: true },
            { name: "Mushroom Masala", price: "1.800", isVeg: true },
            { name: "Navratan Kurma", price: "1.800", isVeg: true },
            { name: "Channa Masala", price: "1.500", isVeg: true },
            { name: "Gobi Masala", price: "1.500", isVeg: true },
            { name: "Veg Makhanwala", price: "1.600", isVeg: true },
            { name: "Baby Corn Masala", price: "1.750", isVeg: true },
            { name: "Bendi Masala", price: "1.800", isVeg: true },
            { name: "Bendi Fry Dry", price: "1.650", isVeg: true },
            { name: "Kadai Mushroom", price: "1.800", isVeg: true },
        ],
    },
    {
        title: "Breads",
        items: [
            { name: "Roti", price: "0.200", isVeg: true },
            { name: "Butter Roti", price: "0.300", isVeg: true },
            { name: "Methi Roti", price: "0.350", isVeg: true },
            { name: "Pudina Roti", price: "0.350", isVeg: true },
            { name: "Garlic Roti", price: "0.500", isVeg: true },
            { name: "Chapathi (1 Pc)", price: "0.150", isVeg: true },
            { name: "Ghee Chapathi (1 Pc)", price: "0.200", isVeg: true },
            { name: "Lachha Paratha", price: "0.400", isVeg: true },
            { name: "Methi Paratha", price: "0.450", isVeg: true },
            { name: "Pudina Paratha", price: "0.450", isVeg: true },
            { name: "Aloo Paratha", price: "0.650", isVeg: true },
            { name: "Gobi Paratha", price: "0.700", isVeg: true },
            { name: "Paneer Paratha", price: "0.850", isVeg: true },
            { name: "Stuffed Paratha", price: "0.700", isVeg: true },
            { name: "Naan", price: "0.300", isVeg: true },
            { name: "Butter Naan", price: "0.400", isVeg: true },
            { name: "Garlic Naan", price: "0.700", isVeg: true },
            { name: "Cheese Naan", price: "0.800", isVeg: true },
            { name: "Garlic Cheese Naan", price: "0.950", isVeg: true },
            { name: "Kulcha", price: "0.350", isVeg: true },
            { name: "Butter Kulcha", price: "0.450", isVeg: true },
            { name: "Masala Kulcha", price: "0.500", isVeg: true },
            { name: "Stuffed Kulcha", price: "0.600", isVeg: true },
            { name: "Onion Kulcha", price: "0.700", isVeg: true },
            { name: "Roti Basket", price: "1.400", isVeg: true },
            { name: "Channa Bathura", price: "1.350", isVeg: true },
            { name: "Extra Bathura", price: "0.500", isVeg: true },
        ],
    },
    {
        title: "North Indian Rice",
        items: [
            { name: "Basmati Rice Plain", price: "0.500", isVeg: true },
            { name: "Ghee Rice", price: "1.300", isVeg: true },
            { name: "Jeera Rice", price: "1.300", isVeg: true },
            { name: "Dal Kichadi", price: "1.500", isVeg: true },
            { name: "Palak Kichadi", price: "1.600", isVeg: true },
            { name: "Veg Pulav", price: "1.400", isVeg: true },
            { name: "Kaju Pulav", price: "1.800", isVeg: true },
            { name: "Kashmiri Pulav", price: "1.700", isVeg: true },
            { name: "Veg Biryani", price: "1.500", isVeg: true },
            { name: "Paneer Biryani", price: "1.800", isVeg: true },
            { name: "Mushroom Biryani", price: "1.800", isVeg: true },
            { name: "Veg Hyderabadi Biryani", price: "1.600", isVeg: true },
            { name: "Mix Vegetable Raitha", price: "0.800", isVeg: true },
            { name: "Pineapple Raitha", price: "0.850", isVeg: true },
            { name: "Boondhi Raitha", price: "0.850", isVeg: true },
            { name: "Green Salad", price: "0.700", isVeg: true },
        ],
    },
    {
        title: "Desserts & Ice Creams",
        items: [
            {
                name: "Gud Bud",
                price: "1.600",
                description: "Three scoops of ice cream topped with a special sauce and nuts",
                isVeg: true
            },
            { name: "Special Falooda", price: "1.800", isVeg: true },
            {
                name: "Banana Split Ice Cream",
                price: "1.500",
                description: "Three scoops of ice cream topped with a special sauce",
                isVeg: true
            },
            { name: "Hot Chocolate Sauce with Vanilla Ice Cream", price: "1.200", isVeg: true },
            {
                name: "Vanilla Nut Sundae",
                price: "1.500",
                description: "Three scoops of ice cream topped with a special sauce",
                isVeg: true
            },
            {
                name: "Chocolate Nut Sundae",
                price: "1.500",
                description: "Three scoops of ice cream topped with a special sauce",
                isVeg: true
            },
            { name: "Fruit Salad with Ice Cream", price: "1.100", isVeg: true },
            { name: "Fruit Salad", price: "0.800", isVeg: true },
            { name: "Gulab Jamoon (2 pcs)", price: "0.600", isVeg: true },
            { name: "Gulab Jamoon (1 pc)", price: "0.300", isVeg: true },
            { name: "Carrot Halwa", price: "1.300", isVeg: true },
            { name: "Kashi Halwa", price: "1.300", isVeg: true },
            { name: "Halubai Udupi Sweet (1 pc)", price: "0.900", isVeg: true },
            { name: "Jamoon With Ice Cream", price: "0.900", isVeg: true },
            { name: "Carrot Halwa With Ice Cream", price: "1.700", isVeg: true },
            { name: "Daal Holige (Weekends)", price: "0.600", isVeg: true },
            { name: "Ice Cream Scoops (Vanilla/Chocolate/Mango/Pista/etc)", price: "0.600", isVeg: true },
        ],
    },
    {
        title: "Cold Beverages",
        items: [
            { name: "Vanilla Milkshake", price: "1.250", isVeg: true },
            { name: "Strawberry Milkshake", price: "1.300", isVeg: true },
            { name: "Butter Scotch Milkshake", price: "1.250", isVeg: true },
            { name: "Chocolate Milkshake", price: "1.250", isVeg: true },
            { name: "Pista Milkshake", price: "1.250", isVeg: true },
            { name: "Rose Milkshake", price: "1.250", isVeg: true },
            { name: "Mango Milkshake", price: "1.300", isVeg: true },
            { name: "Banana Milkshake", price: "1.300", isVeg: true },
            { name: "Apple Milkshake", price: "1.300", isVeg: true },
            { name: "Chickoo Milkshake", price: "1.300", isVeg: true },
            { name: "Apple Juice", price: "1.100", isVeg: true },
            { name: "Orange Juice", price: "1.100", isVeg: true },
            { name: "Pomegranate Juice", price: "1.200", isVeg: true },
            { name: "Mango Juice", price: "1.100", isVeg: true },
            { name: "Water Mellon Juice", price: "1.100", isVeg: true },
            { name: "Pineapple Juice", price: "1.100", isVeg: true },
            { name: "Sweet Melon Juice", price: "1.100", isVeg: true },
            { name: "Lime Juice", price: "0.750", isVeg: true },
            { name: "3 Star (Ginger, Lime, Orange)", price: "1.300", isVeg: true },
            { name: "Cold Badam Milk", price: "1.100", isVeg: true },
            { name: "Cold Coffee", price: "1.300", isVeg: true },
            { name: "Butter Milk", price: "0.450", isVeg: true },
            { name: "Lassi (Sweet / Salt)", price: "0.750", isVeg: true },
            { name: "Mango Lassi", price: "0.900", isVeg: true },
            { name: "Rose Lassi", price: "0.850", isVeg: true },
            { name: "Special Lassi", price: "0.900", isVeg: true },
            { name: "Fresh Lime Soda", price: "0.800", isVeg: true },
            { name: "Mineral Water", price: "0.300", isVeg: true },
            { name: "Soft Drinks", price: "0.400", isVeg: true },
        ],
    },
    {
        title: "Hot Beverages",
        items: [
            { name: "Filter Coffee", price: "0.400", isVeg: true },
            { name: "Mini Filter Coffee", price: "0.250", isVeg: true },
            { name: "Tea / Masala Chai", price: "0.400", isVeg: true },
            { name: "Mini Tea", price: "0.250", isVeg: true },
            { name: "Plain Milk", price: "0.300", isVeg: true },
            { name: "Horlicks / Complan", price: "0.500", isVeg: true },
            { name: "Hot Badam Milk", price: "0.500", isVeg: true },
            { name: "Lemon Tea", price: "0.400", isVeg: true },
            { name: "Black Coffee", price: "0.300", isVeg: true },
            { name: "Black Tea", price: "0.300", isVeg: true },
        ],
    },
];
